name = "PivotTables"
uuid = "05744359-7ec0-46c8-9490-aaa1bc06b10a"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

